### ISSUE TITLE
[Request] Endgame + Botania

### ISSUE THREAD

**Issue by Aringarosa** [Gogo08190/Chroma-Technology#6]
Hello,
first thanks for your time to tinker this mod pack. It keeps me busy.

In the course of the chapter completion, I am through with Botania. Personally, I love the Guardian of Gaia fights. Since the Gaia ingot is Endgame relevant and Vazkii shielded the fight against any automation:
Can you write a recipe for "Mystical Agradditions" what the Gaia Ingot produces in the end? A T6 variant with crux as soil?

**Comment by Gogo08190** [comment]
unfortunately it's up to the developer of Mystical Agradditions to do that I can't do that
