### ISSUE TITLE
zinc ingot 

### ISSUE THREAD

**Issue by Tatakuc** [Gogo08190/Chroma-Technology#7]
Jak udělat Zinc ingot z Extra planets?

**Comment by Gogo08190** [comment]
Wait the Next update

**Comment by Tatakuc** [comment]
Dekuji za odpoved. Počkam na další aktualizaci.

**Comment by Tatakuc** [comment]
Super. Díky.

**Comment by ulreen** [comment]
> Wait the Next update

two years later still no update
